name: Security Check

on:
  schedule:
    - cron: '0 0 * * *' # Roda todos os dias à meia-noite

jobs:
  security_check:
    runs-on: ubuntu-latest

    steps:
      - name: Check for security updates
        uses: github/codeql-action/analyze@v1
        with:
          languages: javascript
